### ISSUE TITLE
貌似已经失效了

### ISSUE THREAD

**Issue by gitzhou** [lurongkai/anti-baidu#11]
Hi
不知道您是否还在维护这个项目，不过目前测试来看功能好像已经失效了。
另外，我同时也测试了coolshell.cn的，同样也失效了。

**Comment by gitzhou** [comment]
再comment一个…刚才用手机试了一下，发现可以…然后电脑试了不行…

**Comment by gitzhou** [comment]
换了几个电脑发现可以了… 逗逼了…
打扰抱歉………

**Comment by lurongkai** [comment]
@gitzhou  :sweat_smile: 这倒是一个奇怪的问题，不过不排队我墙干扰脚本加载的可能

**Comment by gitzhou** [comment]
经过这一天的折腾，我发现这种现象偶尔发生…电脑、手机有时候可以正常…
其实无所谓了，多谢～  嘻嘻    :smiley:
