### ISSUE TITLE
百度搜索替代方案

### ISSUE THREAD

**Issue by suanfazu** [lurongkai/anti-baidu#12]
能否同时给出替代方案？推荐备选：谷歌搜索代理：http://guge.suanfazu.com/

**Comment by lurongkai** [comment]
@suanfazu 经过思考还是放弃添加替代方案，这个小项目本身只是让技术人员放弃百度的搜索引擎，但没有利益相差性，虽然Google是全宇宙最好的SE但是还是决定不在一个小脚本里做太多的事了。还是感谢你的建议。
