### ISSUE TITLE
初入wordpress，想来问问该加在网站哪个文件里呢…

### ISSUE THREAD

**Issue by Rongronggg9** [lurongkai/anti-baidu#15]
不耻下问 [羞羞

**Comment by Rongronggg9** [comment]
可以写在这个项目的Wiki里面嘛

**Comment by ACGunion** [comment]
主题页脚或者主题页眉。添加usage里的代码。

**Comment by Rongronggg9** [comment]
好的 大感谢！

**Comment by LaytonW** [comment]
「不耻下问」好像不是这么用的吧。。

**Comment by Rongronggg9** [comment]
语文不好，不知道……

**Comment by lilydjwg** [comment]
On Mon, Jan 25, 2016 at 10:20:08PM -0800, Layton Wang wrote:
> 「不耻下问」好像不是这么用的吧。。

2333333

-- 
Best regards,
lilydjwg

**Comment by lurongkai** [comment]
@Rongronggg9 直接添加在<head></head>里或者放在<body>标签结束的地方，例如`</body><script src="xxxxx"></script></html>`，后者是推荐的做法。
